// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro/index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Module 0: Introduction to Physical AI',
      items: [
        {
          type: 'doc',
          id: 'intro/chapter-1',
          label: 'Chapter 1: Introduction to Physical AI',
        },
        {
          type: 'doc',
          id: 'intro/chapter-2',
          label: 'Chapter 2: Digital-to-Physical AI Transition',
        },
        {
          type: 'doc',
          id: 'intro/chapter-3',
          label: 'Chapter 3: Embodied Intelligence Concepts',
        },
        {
          type: 'doc',
          id: 'intro/exercises',
          label: 'Exercises',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 - Robotic Nervous System',
      items: [
        {
          type: 'doc',
          id: 'module-1-ros2/index',
          label: 'Module 1 Overview',
        },
        {
          type: 'category',
          label: 'Chapters',
          items: [
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-1',
              label: 'Chapter 1: ROS 2 Fundamentals',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-2',
              label: 'Chapter 2: Nodes and Topics',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-3',
              label: 'Chapter 3: Services and Actions',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-4',
              label: 'Chapter 4: Humanoid Robot Control Systems',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-5',
              label: 'Chapter 5: ROS 2 for Humanoid Robots',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-6',
              label: 'Chapter 6: ROS 2 Pipeline Implementation',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/chapter-7',
              label: 'Chapter 7: ROS 2 Best Practices',
            },
          ],
        },
        {
          type: 'category',
          label: 'Exercises and Examples',
          items: [
            {
              type: 'doc',
              id: 'module-1-ros2/exercises/index',
              label: 'Module 1 Exercises',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/examples/index',
              label: 'Example Code',
            },
          ],
        },
        {
          type: 'category',
          label: 'Hardware and Implementation',
          items: [
            {
              type: 'doc',
              id: 'module-1-ros2/hardware-notes',
              label: 'Hardware Notes',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/gazebo-simulation',
              label: 'Simulation Path',
            },
            {
              type: 'doc',
              id: 'module-1-ros2/real-world-hardware',
              label: 'Real-World Hardware',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo + Unity - Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac - Perception + Navigation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA Robotics - Language to Action',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone',
        },
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [
        {
          type: 'autogenerated',
          dirName: 'appendices',
        },
      ],
    },
  ],
};

module.exports = sidebars;